# Copyright (c) 2026 SAI-Lab / MyCyclingCity
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# @file    backup_config.py
# @author  Roland Rutz
# @note    This code was developed with the assistance of AI (LLMs).

"""Write shell-compatible backup_mcc.conf from MccBackupConfig."""

from __future__ import annotations

from pathlib import Path

from django.conf import settings

from mgmt.models_backup import MccBackupConfig


def get_backup_conf_path() -> Path:
    return Path(
        getattr(
            settings,
            "MCC_BACKUP_CONF_PATH",
            str(Path(getattr(settings, "DATA_DIR", settings.BASE_DIR)) / "backup_mcc.conf"),
        )
    )


def get_backup_script_path() -> Path:
    return Path(settings.BASE_DIR) / "scripts" / "backup_mcc.sh"


def render_backup_conf(config: MccBackupConfig | None = None) -> str:
    config = config or MccBackupConfig.get_config()
    lines = [
        "# Generated by Django MccBackupConfig — do not edit by hand;",
        "# change values in Admin → MCC Backup-Konfiguration.",
        f'SSH_HOST="{config.ssh_host}"',
        f'SSH_USER="{config.ssh_user}"',
        f'SSH_PORT="{int(config.ssh_port)}"',
    ]
    if config.ssh_key and config.ssh_key.strip():
        lines.append(f'SSH_KEY="{config.ssh_key.strip()}"')
    lines.append(f'REMOTE_BACKUP_DIR="{config.remote_backup_dir}"')
    lines.append(f"BACKUP_RETENTION_DAYS={int(config.retention_days)}")
    lines.append("")
    return "\n".join(lines)


def write_backup_conf(config: MccBackupConfig | None = None) -> Path:
    """
    Persist conf file for backup_mcc.sh.

    Returns the written path.
    """
    config = config or MccBackupConfig.get_config()
    path = get_backup_conf_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_backup_conf(config), encoding="utf-8")
    return path
