# Generated by Django 5.2.11 on 2026-08-08 09:16

import django.core.validators
import dynamo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamoBatteryTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('capacity_wh', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Kapazität (Wh)')),
                ('icon_key', models.CharField(default='battery', help_text='CSS/Template-Schlüssel, z. B. phone, tablet, notebook, ebike, house.', max_length=50, verbose_name='Icon-Schlüssel')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('use_daily_energy', models.BooleanField(default=True, help_text='Wenn aktiv: Füllstand aus heutiger Gruppen-Energie. Sonst aus Session-Summe der aktiven Radler.', verbose_name='Tagesenergie verwenden')),
            ],
            options={
                'verbose_name': 'Dynamo-Akku-Ziel',
                'verbose_name_plural': 'Dynamo-Akku-Ziele',
                'ordering': ['sort_order', 'capacity_wh', 'name'],
                'permissions': [('manage_dynamo_batteries', 'Kann Dynamo-Akku-Ziele verwalten')],
            },
        ),
        migrations.CreateModel(
            name='DynamoDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_interval_seconds', models.IntegerField(default=5, help_text='Polling-Intervall für die Dynamo-Live-Anzeige.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(120)], verbose_name='Aktualisierungsintervall (Sekunden)')),
                ('power_cap_w', models.FloatField(default=6.0, help_text='Maximale Nabendynamo-Leistung in der pädagogischen Kennlinie.', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(50.0)], verbose_name='Leistungs-Cap (Watt)')),
                ('power_curve', models.JSONField(default=dynamo.models._default_power_curve, help_text='Liste von Punkten {speed_kmh, power_w} für die virtuelle Dynamo-Kennlinie.', verbose_name='Leistungs-Kennlinie')),
                ('high_power_threshold_w', models.FloatField(default=4.0, help_text='Ab dieser Momentanleistung wird ein Tempo-Blitz angezeigt.', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(50.0)], verbose_name='High-Power-Schwelle (Watt)')),
                ('assumed_speed_kmh_for_estimates', models.FloatField(default=12.0, help_text='Wird genutzt, wenn Energie aus Distanz ohne Intervallgeschwindigkeit geschätzt werden muss (z. B. Alt-Daten).', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(40.0)], verbose_name='Annahme-Geschwindigkeit für Schätzungen (km/h)')),
                ('appliance_equivalents', models.JSONField(default=dynamo.models._default_appliance_equivalents, help_text='Liste {key, label, watts} für „Was könnte man betreiben?“.', verbose_name='Geräte-Äquivalente')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Dynamo-Anzeige',
                'verbose_name_plural': 'Dynamo-Anzeige',
                'permissions': [('manage_dynamo_display', 'Kann Dynamo-Anzeige konfigurieren')],
            },
        ),
    ]
