# Generated by Django 5.2.11 on 2026-08-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0002_seed_dynamo_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamodisplaysettings',
            name='show_cyclist_ride_stats',
            field=models.BooleanField(default=True, help_text='Zeigt Session-Velos und Session-Kilometer auf den Kacheln der aktiven Radler. Per URL überschreibbar: ?ride_stats=1 oder ?ride_stats=0.', verbose_name='Velos und Kilometer bei aktiven Radlern'),
        ),
    ]
