# Generated by Django 5.2.11 on 2026-08-08 09:47

import dynamo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamo', '0003_show_cyclist_ride_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamodisplaysettings',
            name='charger_efficiency_profiles',
            field=models.JSONField(default=dynamo.models._default_charger_efficiency_profiles, help_text='Generische η(v)-Kennlinien ohne Markennamen: {direct|simple|standard|optimized: [{speed_kmh, efficiency}, ...]}.', verbose_name='Ladegerät-Wirkungsgrade'),
        ),
        migrations.AddField(
            model_name='dynamodisplaysettings',
            name='enable_charger_compare',
            field=models.BooleanField(default=True, help_text='Erlaubt Umschalten auf generische Ladegerät-Klassen (Einfach / Standard / Optimiert). Gespeicherte Wh bleiben Dynamo-Rohwerte. URL: ?charger=direct|simple|standard|optimized', verbose_name='Ladegerät-Vergleich (Profi)'),
        ),
    ]
