# Generated by Django 5.2.9 on 2026-01-07 20:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lesbarer Name für dieses Template', max_length=200, unique=True, verbose_name='Template-Name')),
                ('description', models.TextField(blank=True, help_text='Beschreibung, wann dieses Template verwendet werden soll', null=True, verbose_name='Beschreibung')),
                ('template_config', models.JSONField(help_text='Konfigurationswerte für dieses Template', verbose_name='Template-Konfiguration')),
                ('is_active', models.BooleanField(default=True, help_text='Ob dieses Template aktiv und verfügbar ist', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Configuration Template',
                'verbose_name_plural': 'Configuration Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceManagementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Enable daily email notifications for configuration differences', verbose_name='Email Notifications Enabled')),
                ('notification_email', models.EmailField(blank=True, help_text='Email address to receive daily device status reports', max_length=254, null=True, verbose_name='Notification Email Address')),
                ('last_notification_sent', models.DateTimeField(blank=True, help_text='Timestamp of the last notification email sent', null=True, verbose_name='Last Notification Sent')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Device Management Settings',
                'verbose_name_plural': 'Device Management Settings',
            },
        ),
        migrations.CreateModel(
            name='FirmwareImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lesbarer Name für diese Firmware-Version', max_length=200, verbose_name='Firmware-Name')),
                ('version', models.CharField(help_text="Versionskennung (z.B. '1.2.3' oder 'v2.0.1')", max_length=50, unique=True, verbose_name='Version')),
                ('description', models.TextField(blank=True, help_text='Beschreibung der Änderungen und Features in dieser Version', null=True, verbose_name='Beschreibung')),
                ('firmware_file', models.FileField(help_text='Binäre Firmware-Datei (.bin) für ESP32', upload_to='firmware/', verbose_name='Firmware-Datei')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Größe der Firmware-Datei in Bytes', null=True, verbose_name='Dateigröße (Bytes)')),
                ('checksum_md5', models.CharField(blank=True, help_text='MD5-Prüfsumme der Firmware-Datei zur Verifizierung', max_length=32, null=True, verbose_name='MD5-Prüfsumme')),
                ('is_active', models.BooleanField(default=True, help_text='Ob diese Firmware-Version aktiv und für Updates verfügbar ist', verbose_name='Aktiv')),
                ('is_stable', models.BooleanField(default=False, help_text='Ob dies eine stabile Release-Version ist', verbose_name='Stabile Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Firmware Image',
                'verbose_name_plural': 'Firmware Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this webhook', max_length=200, unique=True, verbose_name='Webhook Name')),
                ('url', models.URLField(help_text='URL to send webhook requests to', max_length=500, verbose_name='Webhook URL')),
                ('events', models.JSONField(default=list, help_text='List of events to trigger this webhook', verbose_name='Events')),
                ('secret_key', models.CharField(blank=True, help_text='Secret key for webhook authentication (optional)', max_length=200, null=True, verbose_name='Secret Key')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this webhook is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Webhook Configuration',
                'verbose_name_plural': 'Webhook Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Gerätename')),
                ('display_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Symbolischer Name (Anzeige)')),
                ('distance_total', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15, verbose_name='Laufleistung (km)')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Breitengrad')),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt aktiv')),
                ('last_reported_interval', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Letztes Intervall (km)')),
                ('last_reported_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Bericht')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Interne Kommentare (Admin)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='In Map/Game anzeigen')),
                ('is_km_collection_enabled', models.BooleanField(default=True, help_text='Wenn deaktiviert, werden keine Kilometer für dieses Gerät erfasst', verbose_name='Kilometer-Erfassung aktiv')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group', verbose_name='Zugeordnete Gruppe')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('config_updated', 'Konfiguration aktualisiert'), ('api_key_generated', 'API-Key generiert'), ('api_key_rotated', 'API-Key rotiert'), ('firmware_assigned', 'Firmware zugewiesen'), ('firmware_updated', 'Firmware aktualisiert'), ('config_synced', 'Konfiguration synchronisiert'), ('heartbeat_received', 'Heartbeat empfangen')], max_length=50, verbose_name='Aktion')),
                ('details', models.JSONField(blank=True, help_text='Zusätzliche Details zur Aktion', null=True, verbose_name='Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP-Adresse, von der die Aktion durchgeführt wurde', null=True, verbose_name='IP-Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='iot.device', verbose_name='Gerät')),
                ('user', models.ForeignKey(blank=True, help_text='Benutzer, der die Aktion durchgeführt hat (null für Systemaktionen)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Device Audit Log',
                'verbose_name_plural': 'Device Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfigurationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_config', models.JSONField(help_text='Vom Gerät gemeldete Konfigurationsdaten', verbose_name='Gemeldete Konfiguration')),
                ('has_differences', models.BooleanField(default=False, help_text='Ob dieser Bericht Konfigurationsunterschiede enthält', verbose_name='Hat Unterschiede')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_reports', to='iot.device', verbose_name='Gerät')),
            ],
            options={
                'verbose_name': 'Device Configuration Report',
                'verbose_name_plural': 'Device Configuration Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfigurationDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name des Konfigurationsfelds mit Unterschied', max_length=100, verbose_name='Feldname')),
                ('server_value', models.TextField(blank=True, help_text='Auf dem Server konfigurierter Wert', null=True, verbose_name='Server-Wert')),
                ('device_value', models.TextField(blank=True, help_text='Vom Gerät gemeldeter Wert', null=True, verbose_name='Geräte-Wert')),
                ('is_resolved', models.BooleanField(default=False, help_text='Ob dieser Unterschied behoben wurde', verbose_name='Gelöst')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Gelöst am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_diffs', to='iot.device', verbose_name='Gerät')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs', to='iot.deviceconfigurationreport', verbose_name='Bericht')),
            ],
            options={
                'verbose_name': 'Configuration Difference',
                'verbose_name_plural': 'Configuration Differences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warnung'), ('error', 'Fehler')], default='offline', max_length=20, verbose_name='Status')),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Zeitpunkt des letzten Heartbeat-Signals vom Gerät', null=True, verbose_name='Letzter Heartbeat')),
                ('heartbeat_interval_seconds', models.IntegerField(default=300, help_text='Erwartetes Intervall zwischen Heartbeats in Sekunden', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Erwartetes Heartbeat-Intervall (Sekunden)')),
                ('offline_threshold_seconds', models.IntegerField(default=600, help_text='Gerät gilt als offline, wenn kein Heartbeat für diese Dauer empfangen wurde', validators=[django.core.validators.MinValueValidator(60)], verbose_name='Offline-Schwellenwert (Sekunden)')),
                ('consecutive_failures', models.IntegerField(default=0, help_text='Anzahl aufeinanderfolgender fehlgeschlagener Anfragen', verbose_name='Aufeinanderfolgende Fehler')),
                ('last_error_message', models.TextField(blank=True, null=True, verbose_name='Letzte Fehlermeldung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='iot.device', verbose_name='Gerät')),
            ],
            options={
                'verbose_name': 'Device Health',
                'verbose_name_plural': 'Device Health Status',
            },
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_specific_api_key', models.CharField(blank=True, help_text='Eindeutiger API-Key für dieses Gerät. Wenn nicht gesetzt, verwendet das Gerät den globalen API-Key.', max_length=200, null=True, unique=True, verbose_name='Geräte-API-Key')),
                ('api_key_rotation_enabled', models.BooleanField(default=False, help_text='API-Key automatisch im konfigurierten Intervall rotieren', verbose_name='API-Key-Rotation aktiviert')),
                ('api_key_last_rotated', models.DateTimeField(blank=True, help_text='Zeitstempel der letzten API-Key-Rotation', null=True, verbose_name='API-Key zuletzt rotiert')),
                ('api_key_rotation_interval_days', models.IntegerField(default=90, help_text='Anzahl der Tage zwischen automatischen API-Key-Rotationen', validators=[django.core.validators.MinValueValidator(1)], verbose_name='API-Key-Rotations-Intervall (Tage)')),
                ('apache_base64_auth_key', models.CharField(blank=True, help_text='Base64-kodierter Authentifizierungsschlüssel für Apache Basic Auth (veraltet, verwenden Sie device_specific_api_key)', max_length=200, null=True, verbose_name='Apache Base64 Auth Key (Veraltet)')),
                ('device_name', models.CharField(blank=True, help_text='Name des Geräts, wie auf dem ESP32 konfiguriert', max_length=50, null=True, verbose_name='Gerätename')),
                ('default_id_tag', models.CharField(blank=True, help_text='Standard-ID-Tag-Name für dieses Gerät', max_length=50, null=True, verbose_name='Standard-ID-Tag')),
                ('send_interval_seconds', models.IntegerField(default=60, help_text='Intervall in Sekunden zwischen Datenübertragungen', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sendeintervall (Sekunden)')),
                ('server_url', models.URLField(blank=True, help_text='URL des Server-Endpunkts für Datenübertragung', max_length=500, null=True, verbose_name='Server-URL')),
                ('wifi_ssid', models.CharField(blank=True, help_text='WiFi-Netzwerkname (SSID)', max_length=100, null=True, verbose_name='WLAN SSID')),
                ('wifi_password', models.CharField(blank=True, help_text='WiFi-Netzwerkpasswort', max_length=100, null=True, verbose_name='WLAN-Passwort')),
                ('debug_mode', models.BooleanField(default=False, help_text='Debug-Protokollierung auf dem Gerät aktivieren', verbose_name='Debug-Modus')),
                ('test_mode', models.BooleanField(default=False, help_text='Testdatenübertragungsmodus aktivieren', verbose_name='Test-Modus')),
                ('deep_sleep_seconds', models.IntegerField(default=0, help_text='Zeit in Sekunden für Deep-Sleep-Modus (0 = deaktiviert)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deep-Sleep-Zeit (Sekunden)')),
                ('wheel_size', models.IntegerField(choices=[(20, '20 Zoll'), (24, '24 Zoll'), (26, '26 Zoll'), (28, '28 Zoll')], default=26, help_text='Radgröße in Zoll für Distanzberechnung', verbose_name='Radgröße (Zoll)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Zeitpunkt der letzten erfolgreichen Konfigurationssynchronisation', null=True, verbose_name='Zuletzt synchronisiert')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='iot.device', verbose_name='Device')),
                ('assigned_firmware', models.ForeignKey(blank=True, help_text='Firmware-Image, das diesem Gerät für OTA-Updates zugewiesen wurde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to='iot.firmwareimage', verbose_name='Zugewiesene Firmware')),
            ],
            options={
                'verbose_name': 'Device Configuration',
                'verbose_name_plural': 'Device Configurations',
            },
        ),
    ]
