# Generated by Django 5.2.9 on 2026-01-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_add_request_config_comparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfiguration',
            name='previous_api_key',
            field=models.CharField(blank=True, help_text='Der vorherige API-Key bleibt gültig, bis das Gerät sich erfolgreich mit dem neuen Key authentifiziert hat. Wird automatisch gelöscht, sobald das Gerät den neuen Key verwendet.', max_length=200, null=True, verbose_name='Vorheriger API-Key'),
        ),
        migrations.AlterField(
            model_name='deviceconfiguration',
            name='previous_api_key_expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional: Zeitpunkt für automatische Bereinigung abgelaufener Keys. Wenn nicht gesetzt, bleibt der Key gültig bis das Gerät den neuen Key verwendet.', null=True, verbose_name='Vorheriger API-Key läuft ab am (optional)'),
        ),
    ]
