# Generated by Django 5.2.9 on 2026-01-29 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_remove_version_unique_add_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfiguration',
            name='test_distance_km',
            field=models.FloatField(default=0.01, help_text='Simulierte Distanz in Kilometern für Testmodus. Standard: 0.01 km', validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Test-Distanz (km)'),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='test_interval_seconds',
            field=models.IntegerField(default=5, help_text='Sendeintervall in Sekunden für Testmodus. Standard: 5 Sekunden', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Test-Intervall (Sekunden)'),
        ),
        migrations.AlterField(
            model_name='webhookconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this webhook is active', verbose_name='Aktiv'),
        ),
    ]
