# Generated by Django 5.2.9 on 2026-01-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_deviceconfiguration_test_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemanagementsettings',
            name='iot_device_shared_api_key',
            field=models.CharField(blank=True, help_text='Dedicated API key for IoT devices that can be shared by multiple devices. Used as default key before individual device keys are assigned. Only valid for IoT device endpoints.', max_length=200, null=True, verbose_name='IoT Device Shared API Key'),
        ),
    ]
