# Generated by Django 5.2.9 on 2026-02-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_devicemanagementsettings_iot_device_shared_api_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemanagementsettings',
            options={'verbose_name': 'Geräteverwaltungs-Einstellungen', 'verbose_name_plural': 'Geräteverwaltungs-Einstellungen'},
        ),
        migrations.AlterField(
            model_name='deviceconfiguration',
            name='device_specific_api_key',
            field=models.CharField(blank=True, help_text='Eindeutiger API-Key für dieses Gerät. Wenn nicht gesetzt, verwendet das Gerät den IoT Device Shared API Key (konfiguriert in Geräteverwaltungs-Einstellungen).', max_length=200, null=True, unique=True, verbose_name='Geräte-API-Key'),
        ),
    ]
