# Generated by Django 5.2.9 on 2026-02-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_alter_devicemanagementsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemanagementsettings',
            name='iot_device_shared_api_key',
            field=models.CharField(blank=True, help_text='Dedizierter API-Key für IoT-Geräte, der von mehreren Geräten gleichzeitig verwendet werden kann. Wird als Standard-Key verwendet, bevor individuelle Geräte-Keys zugewiesen werden. Gilt nur für IoT-Geräte-Endpoints, nicht für öffentliche API-Endpoints.', max_length=200, null=True, verbose_name='IoT Device Shared API Key'),
        ),
    ]
