# Generated by Django 5.2.9 on 2026-01-29 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdevice',
            name='assigned_to_group',
            field=models.ForeignKey(blank=True, help_text='TOP-Gruppe, der dieses Kiosk-Gerät zugewiesen ist. Operatoren dieser TOP-Gruppe können das Gerät verwalten. Kann vom System-Admin gesetzt werden, bevor Playlist-Einträge erstellt werden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kiosk_devices', to='api.group', verbose_name='Zugewiesene TOP-Gruppe'),
        ),
        migrations.AlterField(
            model_name='kioskdevice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this device is currently active and should display content', verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='kioskplaylistentry',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this entry is active in the playlist', verbose_name='Aktiv'),
        ),
    ]
