# Generated by Django 5.2.9 on 2026-02-04 16:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_event_delete_eventhistory_and_more'),
        ('eventboard', '0001_initial'),
        ('kiosk', '0002_kioskdevice_assigned_to_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kioskdevice',
            name='brightness',
            field=models.IntegerField(default=100, help_text='Helligkeitsstufe der Anzeige (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Helligkeit'),
        ),
        migrations.AlterField(
            model_name='kioskdevice',
            name='command_queue',
            field=models.JSONField(blank=True, default=list, help_text="JSON-Array mit ausstehenden Hardware-Befehlen (z.B. ['RELOAD', 'SET_BRIGHTNESS:50'])", verbose_name='Befehls-Warteschlange'),
        ),
        migrations.AlterField(
            model_name='kioskdevice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Ob dieses Gerät derzeit aktiv ist und Inhalte anzeigen soll', verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='kioskdevice',
            name='name',
            field=models.CharField(help_text='Lesbarer Name für dieses Kiosk-Gerät', max_length=200, verbose_name='Gerätename'),
        ),
        migrations.AlterField(
            model_name='kioskdevice',
            name='uid',
            field=models.CharField(help_text='Eindeutige Kennung für dieses Gerät (z.B. MAC-Adresse oder Seriennummer)', max_length=100, unique=True, verbose_name='Eindeutige ID'),
        ),
        migrations.AlterField(
            model_name='kioskplaylistentry',
            name='display_duration',
            field=models.IntegerField(default=30, help_text='Wie lange diese Ansicht angezeigt werden soll, bevor zur nächsten gewechselt wird', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Anzeigedauer (Sekunden)'),
        ),
        # Use SeparateDatabaseAndState for event_filter because the table was already renamed
        # in api.0012, so the database FK reference is already correct, we just need to update state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations needed - the table was already renamed from api_event to eventboard_event
                # in api.0012, so the foreign key constraint already points to the correct table.
                # Use RunSQL with empty SQL to satisfy the requirement for database_operations
                migrations.RunSQL(
                    sql=migrations.RunSQL.noop,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='kioskplaylistentry',
                    name='event_filter',
                    field=models.ForeignKey(blank=True, help_text='Optional: Inhalte nach spezifischem Event filtern', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_playlist_entries', to='eventboard.event', verbose_name='Event-Filter'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='kioskplaylistentry',
            name='group_filter',
            field=models.ForeignKey(blank=True, help_text='Optional: Inhalte filtern, um nur Gruppen und Radler anzuzeigen, die zu dieser Hauptgruppe gehören', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_playlist_entries', to='api.group', verbose_name='Gruppen-Filter'),
        ),
        migrations.AlterField(
            model_name='kioskplaylistentry',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Ob dieser Eintrag in der Playlist aktiv ist', verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='kioskplaylistentry',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Anzeigereihenfolge in der Playlist (niedrigere Zahlen zuerst, beginnt bei 1)', verbose_name='Reihenfolge'),
        ),
        migrations.AlterField(
            model_name='kioskplaylistentry',
            name='track_filter',
            field=models.ManyToManyField(blank=True, help_text='Optional: Kartenansicht filtern, um nur ausgewählte Routen anzuzeigen (leer lassen, um alle Routen anzuzeigen)', related_name='kiosk_playlist_entries', to='api.traveltrack', verbose_name='Routen-Filter'),
        ),
        migrations.AlterField(
            model_name='kioskplaylistentry',
            name='view_type',
            field=models.CharField(choices=[('leaderboard', 'Leaderboard'), ('eventboard', 'Eventboard'), ('map', 'Map')], default='leaderboard', help_text='Art der anzuzeigenden Ansicht', max_length=20, verbose_name='Ansichtstyp'),
        ),
    ]
