# Generated by Django 5.2.9 on 2026-01-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_groupmilestoneachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelhistory',
            name='action_type',
            field=models.CharField(choices=[('assigned', 'Zuordnung'), ('aborted', 'Abgebrochen'), ('completed', 'Beendet'), ('restarted', 'Neu gestartet'), ('removed', 'Entfernt')], default='completed', help_text='Art der Aktion, die zu diesem Historieeintrag geführt hat', max_length=20, verbose_name='Aktionstyp'),
        ),
    ]
