# Generated by Django 5.2.9 on 2026-01-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_action_type_to_travel_history'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='travelhistory',
            unique_together=set(),
        ),
    ]
