# Generated by Django 5.2.9 on 2026-01-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_auto_start_to_travel_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmilestoneachievement',
            name='is_redeemed',
            field=models.BooleanField(default=False, help_text='Gibt an, ob die Belohnung bereits eingelöst wurde. Eine Belohnung kann nur einmal eingelöst werden.', verbose_name='Eingelöst'),
        ),
        migrations.AddField(
            model_name='groupmilestoneachievement',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem die Belohnung eingelöst wurde.', null=True, verbose_name='Eingelöst am'),
        ),
        migrations.AddField(
            model_name='groupmilestoneachievement',
            name='reward_text',
            field=models.CharField(blank=True, help_text='Die Belohnung, die zum Zeitpunkt des Erreichens des Meilensteins definiert war. Diese bleibt unverändert, auch wenn die Meilenstein-Belohnung später geändert wird.', max_length=200, null=True, verbose_name='Belohnung'),
        ),
        migrations.AddIndex(
            model_name='groupmilestoneachievement',
            index=models.Index(fields=['group', 'is_redeemed'], name='api_groupmi_group_i_d6bff0_idx'),
        ),
    ]
