# Generated by Django 5.2.9 on 2026-01-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_leaf_group_travel_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptravelstatus',
            name='goal_reached_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem die Gruppe das Ziel erreicht hat. Wird für die Sortierung am Ziel verwendet.', null=True, verbose_name='Ziel erreicht am'),
        ),
    ]
