# Generated by Django 5.2.9 on 2026-01-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_applicationlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applicationlog',
            new_name='mgmt_applic_level_f76100_idx',
            old_name='mgmt_applic_level_t_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationlog',
            new_name='mgmt_applic_logger__064820_idx',
            old_name='mgmt_applic_logger__d3e4f5_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationlog',
            new_name='mgmt_applic_timesta_b6af97_idx',
            old_name='mgmt_applic_timesta_6g7h8i_idx',
        ),
    ]
