# Generated by Django 5.2.9 on 2026-01-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_rename_mgmt_applic_level_t_8a1b2c_idx_mgmt_applic_level_f76100_idx_and_more'),
        ('mgmt', '0005_performance_models'),
    ]

    operations = [
    ]
