# Generated by Django 5.2.9 on 2026-01-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0006_merge_20260122_1627'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='performancemetric',
            name='mgmt_perfor_period_unique',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='mgmt_perfor_period__d63d6d_idx',
            old_name='mgmt_perfor_period__idx',
        ),
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='mgmt_reques_path_2e400b_idx',
            old_name='mgmt_reques_path_ti_idx',
        ),
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='mgmt_reques_status__966d2c_idx',
            old_name='mgmt_reques_status__idx',
        ),
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='mgmt_reques_is_erro_f90b89_idx',
            old_name='mgmt_reques_is_erro_idx',
        ),
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='mgmt_reques_respons_efc051_idx',
            old_name='mgmt_reques_respons_idx',
        ),
        migrations.AlterField(
            model_name='gunicornconfig',
            name='bind_address',
            field=models.CharField(default='127.0.0.1:8000', help_text='Adresse und Port, an die Gunicorn gebunden wird (z.B. 127.0.0.1:8000)', max_length=100, verbose_name='Bind Adresse'),
        ),
        migrations.AlterUniqueTogether(
            name='performancemetric',
            unique_together={('period_type', 'period_start')},
        ),
    ]
