# Generated by Django 5.2.9 on 2026-01-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0007_update_bind_address_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunicornconfig',
            name='bind_address',
            field=models.CharField(default='127.0.0.1:8001', help_text='Adresse und Port, an die Gunicorn gebunden wird (z.B. 127.0.0.1:8001)', max_length=100, verbose_name='Bind Adresse'),
        ),
    ]
