# Generated by Django 5.2.9 on 2026-01-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0008_revert_bind_address_to_8001'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingconfig',
            name='enable_request_logging',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, werden alle HTTP-Requests in der Datenbank gespeichert. Deaktivieren Sie dies, um die Datenbank nicht zu überladen.', verbose_name='Request Logs aktivieren'),
        ),
    ]
