# Generated by Django 5.2.9 on 2026-02-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0013_add_maintenance_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='alert_type',
            field=models.CharField(choices=[('error_rate', 'Fehlerrate'), ('response_time', 'Response Time'), ('memory_usage', 'Memory Usage'), ('cpu_usage', 'CPU Usage'), ('disk_usage', 'Disk Usage'), ('worker_count', 'Worker Count')], max_length=20, verbose_name='Alert Type'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this alert rule is active', verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='gunicornconfig',
            name='log_level',
            field=models.CharField(choices=[('debug', 'DEBUG - Very detailed output'), ('info', 'INFO - Informative messages (default)'), ('warning', 'WARNING - Warnings only'), ('error', 'ERROR - Errors only'), ('critical', 'CRITICAL - Critical errors only')], default='info', help_text='Gunicorn log level. Changes require a server restart.', max_length=10, verbose_name='Log Level'),
        ),
        migrations.AlterField(
            model_name='gunicornconfig',
            name='worker_class',
            field=models.CharField(choices=[('sync', 'sync - Synchronous workers (default)'), ('gthread', 'gthread - Threaded workers (recommended for I/O-intensive applications)'), ('gevent', 'gevent - Async workers (requires gevent)'), ('eventlet', 'eventlet - Async workers (requires eventlet)')], default='sync', help_text='Worker-Klasse für Gunicorn', max_length=20, verbose_name='Worker Klasse'),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='error_count',
            field=models.IntegerField(default=0, verbose_name='Fehleranzahl'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='status_code',
            field=models.IntegerField(db_index=True, verbose_name='Status-Code'),
        ),
    ]
