# Generated by Django 5.2.9 on 2026-07-01 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0015_create_operator_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_device_sessions_on_round_start', models.BooleanField(default=True, help_text='Beim Spiel starten werden aktive Geräte-Sessions der im Game konfigurierten Radler beendet (Standalone-Radler am Counter bleiben aktiv).', verbose_name='Geräte-Sessions bei Rundenstart beenden')),
                ('end_device_sessions_on_round_stop', models.BooleanField(default=False, help_text='Zusätzlich beim Spiel stoppen (oder Timer-Auto-Stopp) Geräte-Sessions beenden.', verbose_name='Geräte-Sessions bei Spielstopp beenden')),
                ('device_session_timeout_minutes', models.PositiveSmallIntegerField(default=5, help_text='Inaktivitäts-Timeout für mcc_worker (Counter-Sessions).', verbose_name='Geräte-Session Timeout (Minuten)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt aktualisiert')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Game Configuration',
                'verbose_name_plural': 'Game Configuration',
            },
        ),
    ]
