# Generated by Django 5.2.9 on 2026-01-29 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='assigned_to_group',
            field=models.ForeignKey(blank=True, help_text='TOP-Gruppe, der dieser Meilenstein zugewiesen ist. Operatoren dieser TOP-Gruppe können den Meilenstein verwalten. Kann vom System-Admin gesetzt werden. Falls nicht gesetzt, wird die Zugehörigkeit über die Route bestimmt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_milestones', to='api.group', verbose_name='Zugewiesene TOP-Gruppe'),
        ),
        migrations.AddField(
            model_name='traveltrack',
            name='assigned_to_group',
            field=models.ForeignKey(blank=True, help_text='TOP-Gruppe, der diese Reiseroute zugewiesen ist. Operatoren dieser TOP-Gruppe können die Route verwalten. Kann vom System-Admin gesetzt werden, bevor GroupTravelStatus Einträge erstellt werden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_travel_tracks', to='api.group', verbose_name='Zugewiesene TOP-Gruppe'),
        ),
    ]
