# Generated by Django 5.2.9 on 2026-02-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_last_session_distance_km_to_hourly_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target_distance_km',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Gesamtes Kilometerziel für dieses Event (optional). Wird für Fortschrittsanzeige verwendet.', max_digits=15, null=True, verbose_name='Kilometerziel'),
        ),
    ]
