# Generated by Django 5.2.9 on 2026-02-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_event_target_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeventstatus',
            name='goal_reached_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem die Gruppe das Event-Ziel erreicht hat. Wird für die Sortierung auf dem Podest verwendet.', null=True, verbose_name='Ziel erreicht am'),
        ),
    ]
