# Generated by Django 5.2.9 on 2026-02-04 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_group_event_status_goal_reached_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='update_interval_seconds',
            field=models.IntegerField(default=30, help_text='Aktualisierungsintervall für das Eventboard in Sekunden (5-300). Standard: 30 Sekunden.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='Update-Intervall (Sekunden)'),
        ),
    ]
