# Generated by Django 5.2.9 on 2026-02-04 13:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_update_interval_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='left_logo',
            field=models.ImageField(blank=True, help_text='Logo/Bild, das links neben dem Event-Titel angezeigt wird (max. 500x500px)', null=True, upload_to='event_logos/', validators=[api.models.validate_logo_size], verbose_name='Logo links'),
        ),
        migrations.AddField(
            model_name='event',
            name='right_logo',
            field=models.ImageField(blank=True, help_text='Logo/Bild, das rechts neben dem Event-Titel angezeigt wird (max. 500x500px)', null=True, upload_to='event_logos/', validators=[api.models.validate_logo_size], verbose_name='Logo rechts'),
        ),
    ]
