# Generated by Django 5.2.9 on 2026-02-04 14:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event_left_logo_event_right_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhistory',
            name='best_leaf_group',
            field=models.ForeignKey(blank=True, help_text='Die Leaf-Gruppe (z.B. Klasse) mit den meisten gestrampelten Kilometern in dieser TOP-Gruppe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_history_as_best_leaf', to='api.group', verbose_name='Beste Leaf-Gruppe'),
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='best_leaf_group_goal_reached_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem die beste Leaf-Gruppe das Event-Ziel erreicht hat', null=True, verbose_name='Ziel erreicht am (Beste Leaf-Gruppe)'),
        ),
        migrations.AddField(
            model_name='groupeventstatus',
            name='best_leaf_group',
            field=models.ForeignKey(blank=True, help_text='Die Leaf-Gruppe (z.B. Klasse) mit den meisten gestrampelten Kilometern in dieser TOP-Gruppe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_statuses_as_best_leaf', to='api.group', verbose_name='Beste Leaf-Gruppe'),
        ),
        migrations.AddField(
            model_name='groupeventstatus',
            name='best_leaf_group_goal_reached_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem die beste Leaf-Gruppe das Event-Ziel erreicht hat', null=True, verbose_name='Ziel erreicht am (Beste Leaf-Gruppe)'),
        ),
        migrations.CreateModel(
            name='LeafGroupEventContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_event_distance', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), help_text='Die von dieser Leaf-Gruppe während des aktuellen Events zurückgelegte Distanz', max_digits=15, verbose_name='Aktuelle Event-Distanz (km)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_group_contributions', to='api.event', verbose_name='Event')),
                ('leaf_group', models.ForeignKey(help_text='Die Leaf-Gruppe (z.B. Klasse), die Kilometer beiträgt', on_delete=django.db.models.deletion.CASCADE, related_name='event_contributions', to='api.group', verbose_name='Leaf-Gruppe')),
            ],
            options={
                'verbose_name': 'Leaf-Gruppe Event-Beitrag',
                'verbose_name_plural': 'Leaf-Gruppe Event-Beiträge',
                'indexes': [models.Index(fields=['leaf_group', 'event'], name='api_leafgro_leaf_gr_46f73c_idx'), models.Index(fields=['event', '-current_event_distance'], name='api_leafgro_event_i_b62a30_idx')],
                'unique_together': {('leaf_group', 'event')},
            },
        ),
    ]
