# Generated by Django 5.2.9 on 2026-02-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_eventhistory_best_leaf_group_and_more'),
        ('kiosk', '0003_alter_kioskdevice_brightness_and_more'),
        ('eventboard', '0001_initial'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to rename tables in DB but only update state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Rename tables from api_* to eventboard_* to preserve data
                migrations.RunSQL(
                    # SQLite: Rename tables from api_* to eventboard_*
                    sql=[
                        "ALTER TABLE api_event RENAME TO eventboard_event;",
                        "ALTER TABLE api_eventhistory RENAME TO eventboard_eventhistory;",
                        "ALTER TABLE api_groupeventstatus RENAME TO eventboard_groupeventstatus;",
                        "ALTER TABLE api_leafgroupeventcontribution RENAME TO eventboard_leafgroupeventcontribution;",
                    ],
                    reverse_sql=[
                        "ALTER TABLE eventboard_event RENAME TO api_event;",
                        "ALTER TABLE eventboard_eventhistory RENAME TO api_eventhistory;",
                        "ALTER TABLE eventboard_groupeventstatus RENAME TO api_groupeventstatus;",
                        "ALTER TABLE eventboard_leafgroupeventcontribution RENAME TO api_leafgroupeventcontribution;",
                    ],
                ),
            ],
            state_operations=[
                # Remove models from api app state (tables already renamed to eventboard_*)
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventHistory',
        ),
        migrations.DeleteModel(
            name='GroupEventStatus',
        ),
        migrations.DeleteModel(
            name='LeafGroupEventContribution',
                ),
            ],
        ),
    ]
