# Generated by Django 5.2.9 on 2026-02-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_event_delete_eventhistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmilestoneachievement',
            options={'ordering': ['-reached_at'], 'verbose_name': 'Erreichte Meilensteine', 'verbose_name_plural': 'Erreichte Meilensteine'},
        ),
        migrations.AlterModelOptions(
            name='grouptravelstatus',
            options={'verbose_name': 'Gruppen-Status', 'verbose_name_plural': 'Gruppen-Status'},
        ),
        migrations.AlterModelOptions(
            name='leafgrouptravelcontribution',
            options={'verbose_name': 'Leaf-Gruppe Beitrag', 'verbose_name_plural': 'Leaf-Gruppe Beiträge'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['distance_km'], 'verbose_name': 'Meilenstein', 'verbose_name_plural': 'Meilensteine'},
        ),
        migrations.AlterModelOptions(
            name='travelhistory',
            options={'ordering': ['-end_time'], 'verbose_name': 'Historie', 'verbose_name_plural': 'Historien'},
        ),
        migrations.AlterModelOptions(
            name='traveltrack',
            options={'verbose_name': 'Route', 'verbose_name_plural': 'Routen'},
        ),
    ]
