# Generated by Django 5.2.9 on 2026-02-15 15:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_unique_name_constraints'),
        ('iot', '0013_alter_devicemanagementsettings_iot_device_shared_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearEndSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(help_text='Datum/Zeitpunkt, zu dem der Abschluss durchgeführt wurde', verbose_name='Abschlussdatum')),
                ('period_start_date', models.DateTimeField(help_text='Startdatum der abgeschlossenen Periode (z.B. Schuljahresbeginn)', verbose_name='Perioden-Startdatum')),
                ('period_end_date', models.DateTimeField(help_text='Enddatum der abgeschlossenen Periode (z.B. Schuljahresende)', verbose_name='Perioden-Enddatum')),
                ('period_type', models.CharField(choices=[('school_year', 'Schuljahr'), ('calendar_year', 'Kalenderjahr')], max_length=20, verbose_name='Periodentyp')),
                ('group_total_km', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15, verbose_name='Gruppen-Gesamt-KM')),
                ('group_total_coins', models.IntegerField(default=0, verbose_name='Gruppen-Gesamt-Coins')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('is_undone', models.BooleanField(default=False, help_text='Gibt an, ob dieser Abschluss rückgängig gemacht wurde', verbose_name='Rückgängig gemacht')),
                ('undone_at', models.DateTimeField(blank=True, null=True, verbose_name='Rückgängig gemacht am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('group', models.ForeignKey(help_text='Die TOP-Gruppe (Schule oder Einrichtung), für die dieser Abschluss erstellt wurde', on_delete=django.db.models.deletion.CASCADE, related_name='year_end_snapshots', to='api.group', verbose_name='TOP-Gruppe')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Rückgängig gemacht von')),
            ],
            options={
                'verbose_name': 'Jahresabschluss',
                'verbose_name_plural': 'Jahresabschlüsse',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='YearEndSnapshotDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_total', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15, verbose_name='Gesamt-KM zum Abschlusszeitpunkt')),
                ('coins_total', models.IntegerField(default=0, verbose_name='Gesamt-Coins zum Abschlusszeitpunkt')),
                ('cyclist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_end_snapshot_details', to='api.cyclist', verbose_name='Radler')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_end_snapshot_details', to='iot.device', verbose_name='Gerät')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_end_snapshot_details', to='api.group', verbose_name='Subgruppe')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.yearendsnapshot', verbose_name='Jahresabschluss')),
            ],
            options={
                'verbose_name': 'Jahresabschluss-Detail',
                'verbose_name_plural': 'Jahresabschluss-Details',
            },
        ),
        migrations.AddIndex(
            model_name='yearendsnapshot',
            index=models.Index(fields=['group', '-snapshot_date'], name='api_yearend_group_i_518389_idx'),
        ),
        migrations.AddIndex(
            model_name='yearendsnapshot',
            index=models.Index(fields=['group', 'is_undone', '-snapshot_date'], name='api_yearend_group_i_0c0f80_idx'),
        ),
        migrations.AddIndex(
            model_name='yearendsnapshotdetail',
            index=models.Index(fields=['snapshot', 'group'], name='api_yearend_snapsho_e60af8_idx'),
        ),
        migrations.AddIndex(
            model_name='yearendsnapshotdetail',
            index=models.Index(fields=['snapshot', 'cyclist'], name='api_yearend_snapsho_57d91a_idx'),
        ),
        migrations.AddIndex(
            model_name='yearendsnapshotdetail',
            index=models.Index(fields=['snapshot', 'device'], name='api_yearend_snapsho_d2fc94_idx'),
        ),
        migrations.AddConstraint(
            model_name='yearendsnapshotdetail',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cyclist__isnull', True), ('device__isnull', True), ('group__isnull', False)), models.Q(('cyclist__isnull', False), ('device__isnull', True), ('group__isnull', True)), models.Q(('cyclist__isnull', True), ('device__isnull', False), ('group__isnull', True)), _connector='OR'), name='year_end_snapshot_detail_must_have_one'),
        ),
    ]
