# Generated by Django 5.2.9 on 2026-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_velos_phase_c_remove_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclist',
            name='is_operator_tag',
            field=models.BooleanField(default=False, help_text='Scan at an MCC counter resets the device to its default cyclist (no riding session, no Velos credit).', verbose_name='Operator-RFID-Tag'),
        ),
    ]
