# Generated by Django 5.2.11 on 2026-08-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_enable_eventboard_km_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='luanti_username',
            field=models.CharField(
                blank=True,
                help_text='Team-Key für Luanti-Shop/Velos (Leaf-Gruppen).',
                max_length=100,
                null=True,
                verbose_name='Luanti-Name (Gruppe)',
            ),
        ),
    ]
