# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_luanti_integration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupVeloTransfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batch_id", models.UUIDField(db_index=True, verbose_name="Batch-ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("consolidate", "Konsolidierung (Umbuchung)"),
                            ("zero", "Spendable nullen"),
                        ],
                        default="consolidate",
                        max_length=16,
                        verbose_name="Aktion",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Betrag (Spendable)")),
                ("reason", models.CharField(max_length=255, verbose_name="Grund / Event")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Zeitpunkt")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ausgeführt von",
                    ),
                ),
                (
                    "source_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="velo_transfers_out",
                        to="api.group",
                        verbose_name="Quelle",
                    ),
                ),
                (
                    "target_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="velo_transfers_in",
                        to="api.group",
                        verbose_name="Ziel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gruppen-Velo-Transfer",
                "verbose_name_plural": "Gruppen-Velo-Transfers",
                "ordering": ["-created_at", "-id"],
                "permissions": [
                    ("transfer_group_velos", "Ausgebbare Gruppen-Velos konsolidieren/umbuchen")
                ],
                "indexes": [
                    models.Index(fields=["batch_id"], name="api_gvt_batch_id_idx"),
                    models.Index(fields=["created_at"], name="api_gvt_created_at_idx"),
                ],
            },
        ),
    ]
