# Generated by Django 5.2.9 on 2026-01-07 20:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this Kiosk device', max_length=200, verbose_name='Gerätename')),
                ('uid', models.CharField(help_text='Unique identifier for this device (e.g., MAC address or serial number)', max_length=100, unique=True, verbose_name='Unique ID')),
                ('brightness', models.IntegerField(default=100, help_text='Display brightness level (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Brightness')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device is currently active and should display content', verbose_name='Active')),
                ('command_queue', models.JSONField(blank=True, default=list, help_text="JSON array of pending hardware commands (e.g., ['RELOAD', 'SET_BRIGHTNESS:50'])", verbose_name='Command Queue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KioskPlaylistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_type', models.CharField(choices=[('leaderboard', 'Leaderboard'), ('eventboard', 'Eventboard'), ('map', 'Map')], default='leaderboard', help_text='Type of view to display', max_length=20, verbose_name='View Type')),
                ('display_duration', models.IntegerField(default=30, help_text='How long to display this view before rotating to the next', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Display Duration (seconds)')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order in the playlist (lower numbers first, starts at 1)', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this entry is active in the playlist', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='kiosk.kioskdevice', verbose_name='Kiosk Device')),
                ('event_filter', models.ForeignKey(blank=True, help_text='Optional: Filter content by specific event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_playlist_entries', to='api.event', verbose_name='Event Filter')),
                ('group_filter', models.ForeignKey(blank=True, help_text='Optional: Filter content to show only groups and cyclists belonging to this master group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_playlist_entries', to='api.group', verbose_name='Group Filter')),
                ('track_filter', models.ManyToManyField(blank=True, help_text='Optional: Filter map view to show only selected tracks (leave empty to show all tracks)', related_name='kiosk_playlist_entries', to='api.traveltrack', verbose_name='Track Filter')),
            ],
            options={
                'verbose_name': 'Playlist Entry',
                'verbose_name_plural': 'Playlist Entries',
                'ordering': ['device', 'order', 'id'],
                'unique_together': {('device', 'order')},
            },
        ),
    ]
