# Generated by Django 5.2.9 on 2026-02-04 16:58

import django.core.validators
import django.db.models.deletion
import eventboard.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0010_eventhistory_best_leaf_group_and_more'),
    ]

    operations = [
        # Tables already exist (renamed from api_* to eventboard_* in api.0012)
        # We only update the Django state here, no database operations
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No database operations - tables already exist
            state_operations=[
                migrations.CreateModel(
                    name='Event',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200, verbose_name='Event-Name')),
                        ('event_type', models.CharField(choices=[('school_festival', 'Schulfest'), ('celebration', 'Feier'), ('fundraising', 'Spendensammeln'), ('competition', 'Wettbewerb'), ('other', 'Sonstiges')], default='other', max_length=50, verbose_name='Event-Typ')),
                        ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                        ('is_visible_on_map', models.BooleanField(default=True, verbose_name='In Map/Game anzeigen')),
                        ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Startzeitpunkt')),
                        ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Endzeitpunkt')),
                        ('hide_after_date', models.DateTimeField(blank=True, help_text='Events werden nach diesem Datum nicht mehr in der Karte angezeigt, auch wenn sie noch aktiv sind', null=True, verbose_name='Ab diesem Datum nicht mehr anzeigen')),
                        ('target_distance_km', models.DecimalField(blank=True, decimal_places=5, help_text='Gesamtes Kilometerziel für dieses Event (optional). Wird für Fortschrittsanzeige verwendet.', max_digits=15, null=True, verbose_name='Kilometerziel')),
                        ('update_interval_seconds', models.IntegerField(default=30, help_text='Aktualisierungsintervall für das Eventboard in Sekunden (5-300). Standard: 30 Sekunden.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='Update-Intervall (Sekunden)')),
                        ('left_logo', models.ImageField(blank=True, help_text='Logo/Bild, das links neben dem Event-Titel angezeigt wird (max. 500x500px)', null=True, upload_to='event_logos/', validators=[eventboard.models.validate_logo_size], verbose_name='Logo links')),
                        ('right_logo', models.ImageField(blank=True, help_text='Logo/Bild, das rechts neben dem Event-Titel angezeigt wird (max. 500x500px)', null=True, upload_to='event_logos/', validators=[eventboard.models.validate_logo_size], verbose_name='Logo rechts')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                    ],
                    options={
                        'verbose_name': 'Event',
                        'verbose_name_plural': 'Events',
                        'ordering': ['-start_time', 'name'],
                    },
                ),
                migrations.CreateModel(
                    name='EventHistory',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('start_time', models.DateTimeField(verbose_name='Startzeitpunkt')),
                        ('end_time', models.DateTimeField(verbose_name='Endzeitpunkt')),
                        ('total_distance_km', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15, verbose_name='Gesammelte Kilometer')),
                        ('best_leaf_group_goal_reached_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem die beste Leaf-Gruppe das Event-Ziel erreicht hat', null=True, verbose_name='Ziel erreicht am (Beste Leaf-Gruppe)')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                        ('best_leaf_group', models.ForeignKey(blank=True, help_text='Die Leaf-Gruppe (z.B. Klasse) mit den meisten gestrampelten Kilometern in dieser TOP-Gruppe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_history_as_best_leaf', to='api.group', verbose_name='Beste Leaf-Gruppe')),
                        ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='eventboard.event', verbose_name='Event')),
                        ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_history', to='api.group', verbose_name='Gruppe')),
                    ],
                    options={
                        'verbose_name': 'Events - History',
                        'verbose_name_plural': 'Events - Histories',
                        'ordering': ['-end_time'],
                        'unique_together': {('event', 'group', 'start_time')},
                    },
                ),
                migrations.CreateModel(
                    name='GroupEventStatus',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('current_distance_km', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15, verbose_name='Aktuelle Distanz (km)')),
                        ('start_km_offset', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15, verbose_name='Start-Offset (km)')),
                        ('goal_reached_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem die Gruppe das Event-Ziel erreicht hat. Wird für die Sortierung auf dem Podest verwendet.', null=True, verbose_name='Ziel erreicht am')),
                        ('best_leaf_group_goal_reached_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem die beste Leaf-Gruppe das Event-Ziel erreicht hat', null=True, verbose_name='Ziel erreicht am (Beste Leaf-Gruppe)')),
                        ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Beigetreten am')),
                        ('best_leaf_group', models.ForeignKey(blank=True, help_text='Die Leaf-Gruppe (z.B. Klasse) mit den meisten gestrampelten Kilometern in dieser TOP-Gruppe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_statuses_as_best_leaf', to='api.group', verbose_name='Beste Leaf-Gruppe')),
                        ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_statuses', to='eventboard.event', verbose_name='Event')),
                        ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_statuses', to='api.group', verbose_name='Gruppe')),
                    ],
                    options={
                        'verbose_name': 'Gruppen-Event-Status',
                        'verbose_name_plural': 'Gruppen-Event-Status',
                        'unique_together': {('group', 'event')},
                    },
                ),
                migrations.CreateModel(
                    name='LeafGroupEventContribution',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('current_event_distance', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), help_text='Die von dieser Leaf-Gruppe während des aktuellen Events zurückgelegte Distanz', max_digits=15, verbose_name='Aktuelle Event-Distanz (km)')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                        ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_group_contributions', to='eventboard.event', verbose_name='Event')),
                        ('leaf_group', models.ForeignKey(help_text='Die Leaf-Gruppe (z.B. Klasse), die Kilometer beiträgt', on_delete=django.db.models.deletion.CASCADE, related_name='event_contributions', to='api.group', verbose_name='Leaf-Gruppe')),
                    ],
                    options={
                        'verbose_name': 'Leaf-Gruppe Event-Beitrag',
                        'verbose_name_plural': 'Leaf-Gruppe Event-Beiträge',
                        'indexes': [models.Index(fields=['leaf_group', 'event'], name='eventboard__leaf_gr_3af3d2_idx'), models.Index(fields=['event', '-current_event_distance'], name='eventboard__event_i_34e159_idx')],
                        'unique_together': {('leaf_group', 'event')},
                    },
                ),
            ],
        ),
    ]
