# Generated by Django 5.2.9 on 2026-02-05 09:00

import django.db.models.deletion
from django.db import migrations, models


def assign_top_groups_to_existing_events(apps, schema_editor):
    """
    Assign existing events to the first TOP group (parent=None) if available.
    If no TOP groups exist, leave events without top_group (they will need manual assignment).
    """
    Event = apps.get_model('eventboard', 'Event')
    Group = apps.get_model('api', 'Group')
    
    # Find the first TOP group (parent=None, is_visible=True)
    top_group = Group.objects.filter(parent__isnull=True, is_visible=True).first()
    
    if top_group:
        # Assign all events without top_group to this TOP group
        Event.objects.filter(top_group__isnull=True).update(top_group=top_group)


def reverse_assign_top_groups(apps, schema_editor):
    """Reverse migration: Remove top_group assignments."""
    Event = apps.get_model('eventboard', 'Event')
    Event.objects.all().update(top_group=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_event_delete_eventhistory_and_more'),
        ('eventboard', '0001_initial'),
    ]

    operations = [
        # Step 1: Add top_group field as nullable
        migrations.AddField(
            model_name='event',
            name='top_group',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='events',
                to='api.group',
                verbose_name='TOP-Gruppe',
                help_text='Die TOP-Gruppe (Hauptgruppe ohne übergeordnete Gruppe), der dieses Event zugeordnet ist. Operatoren können nur Events ihrer verwalteten TOP-Gruppen erstellen und bearbeiten.'
            ),
        ),
        # Step 2: Assign existing events to a TOP group
        migrations.RunPython(assign_top_groups_to_existing_events, reverse_assign_top_groups),
        # Step 3: Make top_group required (not nullable)
        migrations.AlterField(
            model_name='event',
            name='top_group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='events',
                to='api.group',
                verbose_name='TOP-Gruppe',
                help_text='Die TOP-Gruppe (Hauptgruppe ohne übergeordnete Gruppe), der dieses Event zugeordnet ist. Operatoren können nur Events ihrer verwalteten TOP-Gruppen erstellen und bearbeiten.'
            ),
        ),
    ]
