# Generated by Django 5.2.9 on 2026-02-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minecraftoutboxevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Minecraft Outbox Event', 'verbose_name_plural': 'Minecraft Outbox Events'},
        ),
        migrations.AlterModelOptions(
            name='minecraftplayerscoreboardsnapshot',
            options={'ordering': ['player_name'], 'verbose_name': 'Minecraft Scoreboard Snapshot', 'verbose_name_plural': 'Minecraft Scoreboard Snapshots'},
        ),
        migrations.AlterModelOptions(
            name='minecraftworkerstate',
            options={'verbose_name': 'Minecraft Worker State', 'verbose_name_plural': 'Minecraft Worker States'},
        ),
    ]
