# Generated by Django 5.2.11 on 2026-07-19 14:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0011_rcon_preset_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftPlayAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(help_text='Eindeutiger Key (v1 oft gleich Kurzname, später echte RFID-UID)', max_length=50, unique=True, verbose_name='RFID-UID')),
                ('short_name', models.CharField(help_text='Minecraft-/AuthMe-Login, z. B. Arena1', max_length=32, unique=True, verbose_name='Kurzname / Login')),
                ('display_name', models.CharField(blank=True, help_text='Leer = Kurzname', max_length=64, verbose_name='Anzeigename')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
            ],
            options={
                'verbose_name': 'Minecraft Play Account',
                'verbose_name_plural': 'Minecraft Play Accounts',
                'ordering': ['sort_order', 'short_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='minecraftshopitem',
            options={'ordering': ['category', 'sort_order', 'esgui_item_key', 'material'], 'verbose_name': 'Minecraft Shop Item', 'verbose_name_plural': 'Minecraft Shop Items'},
        ),
        migrations.CreateModel(
            name='MCSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(db_index=True, help_text='AuthMe-/MC-Login (short_name oder Team-mc_username)', max_length=100, verbose_name='Account-Name')),
                ('account_type', models.CharField(choices=[('PLAYER', 'Spieler (Arena)'), ('BUILDER', 'Bau-Team')], max_length=16, verbose_name='Account-Typ')),
                ('timestamp_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Dauer (Minuten)')),
                ('ends_at', models.DateTimeField(db_index=True, verbose_name='Geplantes Ende')),
                ('timestamp_end', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächliches Ende')),
                ('status', models.CharField(choices=[('READY', 'Bereit'), ('ACTIVE', 'Aktiv'), ('FINISHED', 'Beendet')], db_index=True, default='READY', max_length=16, verbose_name='Status')),
                ('source', models.CharField(choices=[('admin', 'Admin-GUI'), ('rfid', 'RFID-Scan'), ('system', 'System')], default='admin', max_length=16, verbose_name='Auslöser')),
                ('last_error', models.TextField(blank=True, verbose_name='Letzter Fehler')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gestartet von')),
            ],
            options={
                'verbose_name': 'Minecraft Session',
                'verbose_name_plural': 'Minecraft Sessions',
                'ordering': ['-timestamp_start'],
                'indexes': [models.Index(fields=['status', 'ends_at'], name='minecraft_mcsess_status_ends')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('account_name',), name='minecraft_unique_active_session_per_account')],
            },
        ),
    ]
