# Generated by Django 5.2.9 on 2026-07-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0012_play_account_and_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minecraftintegrationconfig',
            options={'permissions': [('access_minecraft_control', 'Minecraft Control öffnen'), ('access_minecraft_city', 'Stadtsteuerung öffnen'), ('access_minecraft_shop', 'Shop-Betrieb öffnen'), ('run_free_rcon', 'Freie RCON-Befehle senden'), ('manage_player_sessions', 'Spieler-Sessions verwalten'), ('manage_builder_sessions', 'Builder-Sessions verwalten')], 'verbose_name': 'Minecraft Integration Config', 'verbose_name_plural': 'Minecraft Integration Config'},
        ),
    ]
