# Generated by Django 5.2.11 on 2026-07-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0018_builder_authme_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcsession',
            options={'ordering': ['-timestamp_start'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='minecraftbridgeconnection',
            options={'verbose_name': 'Bridge-Verbindung', 'verbose_name_plural': 'Bridge-Verbindungen'},
        ),
        migrations.AlterModelOptions(
            name='minecraftbuilderaccount',
            options={'verbose_name': 'Bau-Account', 'verbose_name_plural': 'Bau-Accounts'},
        ),
        migrations.AlterModelOptions(
            name='minecraftintegrationconfig',
            options={'permissions': [('access_minecraft_control', 'Control öffnen'), ('access_minecraft_city', 'Stadtsteuerung öffnen'), ('access_minecraft_shop', 'Shop-Betrieb öffnen'), ('run_free_rcon', 'Freie RCON-Befehle senden'), ('manage_player_sessions', 'Spieler-Sessions verwalten'), ('manage_builder_sessions', 'Builder-Sessions verwalten')], 'verbose_name': 'Integration', 'verbose_name_plural': 'Integration'},
        ),
        migrations.AlterModelOptions(
            name='minecraftoutboxevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Outbox-Ereignis', 'verbose_name_plural': 'Outbox'},
        ),
        migrations.AlterModelOptions(
            name='minecraftplayaccount',
            options={'ordering': ['sort_order', 'short_name'], 'verbose_name': 'Spieler-Account', 'verbose_name_plural': 'Spieler-Accounts'},
        ),
        migrations.AlterModelOptions(
            name='minecraftplayerscoreboardsnapshot',
            options={'ordering': ['player_name'], 'verbose_name': 'Scoreboard-Snapshot', 'verbose_name_plural': 'Scoreboard'},
        ),
        migrations.AlterModelOptions(
            name='minecraftrconpreset',
            options={'ordering': ['category', 'sort_order', 'name'], 'permissions': [('run_rconpreset', 'RCON-Presets ausführen'), ('change_system_rconpreset', 'System-Presets bearbeiten'), ('delete_system_rconpreset', 'System-Presets löschen'), ('export_rconpreset', 'RCON-Presets exportieren')], 'verbose_name': 'RCON-Preset', 'verbose_name_plural': 'RCON-Presets'},
        ),
        migrations.AlterModelOptions(
            name='minecraftshopcategory',
            options={'ordering': ['sort_order', 'slug'], 'verbose_name': 'Shop-Kategorie', 'verbose_name_plural': 'Shop-Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='minecraftshopitem',
            options={'ordering': ['category', 'sort_order', 'esgui_item_key', 'material'], 'verbose_name': 'Shop-Artikel', 'verbose_name_plural': 'Shop-Artikel'},
        ),
        migrations.AlterModelOptions(
            name='minecraftworkerstate',
            options={'verbose_name': 'Worker-Status', 'verbose_name_plural': 'Worker'},
        ),
    ]
