# Generated by Django — prefer_spectator + session gamemode tracking (Phase 2)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0026_arena_cart_label_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="minecraftplayaccount",
            name="prefer_spectator",
            field=models.BooleanField(
                default=False,
                help_text="Nächste Session startet im Spectator-Modus (Adventure bei Play).",
                verbose_name="Spectator-Modus bevorzugen",
            ),
        ),
        migrations.AddField(
            model_name="minecraftteamregistration",
            name="prefer_spectator",
            field=models.BooleanField(
                default=False,
                help_text="Nächste Session startet im Spectator-Modus (Survival bei Bau).",
                verbose_name="Spectator-Modus bevorzugen",
            ),
        ),
        migrations.AddField(
            model_name="mcsession",
            name="gamemode_spectator",
            field=models.BooleanField(
                default=False,
                help_text="Aktueller Gamemode während der Session (Toggle Adventure/Survival ↔ Spectator).",
                verbose_name="Spectator aktiv",
            ),
        ),
    ]
