# Generated by Django 5.2 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0030_shop_item_min_velos"),
    ]

    operations = [
        migrations.AddField(
            model_name="minecraftintegrationconfig",
            name="builder_session_active_hint",
            field=models.CharField(
                blank=True,
                default="⚠️ Session ist aktiv!",
                help_text=(
                    "Gelber Hinweis auf dem Bau-Sessions-Dashboard bei laufender Session. "
                    "Leer lassen = Hinweis ausblenden."
                ),
                max_length=200,
                verbose_name="Hinweis aktive Bau-Session",
            ),
        ),
    ]
