# Generated by Django 5.2

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0033_manage_minecraft_proxy_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="minecraftintegrationconfig",
            name="proxy_presence_poll_seconds",
            field=models.PositiveIntegerField(
                default=10,
                help_text=(
                    "Wie oft die Session-Dashboards den Spieler-Standort per Velocity-RCON "
                    "(glist) abfragen. Minimum 2 Sekunden, Standard 10."
                ),
                validators=[MinValueValidator(2)],
                verbose_name="Update-Intervall Velocity-RCON (s)",
            ),
        ),
    ]
