# Generated by Django 5.2

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0034_proxy_presence_poll_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="minecraftintegrationconfig",
            name="session_login_wait_seconds",
            field=models.PositiveIntegerField(
                default=45,
                help_text=(
                    "Nach Velocity-Send / AuthMe-Login wartet die Freigabe so lange, "
                    "bis der Spieler auf dem Paper-Server online ist "
                    "(Maus-Klick / Client-Fokus). Minimum 5, Standard 45."
                ),
                validators=[MinValueValidator(5)],
                verbose_name="Wartezeit nach Freigabe (s)",
            ),
        ),
        migrations.AlterField(
            model_name="minecraftintegrationconfig",
            name="proxy_presence_poll_seconds",
            field=models.PositiveIntegerField(
                default=10,
                help_text=(
                    "Wie oft die Session-Dashboards den Spieler-Standort per Velocity-RCON "
                    "(glist) abfragen, wenn niemand im Warteraum wartet. "
                    "Bei Warteraum-Status wird automatisch häufiger abgefragt. "
                    "Minimum 2 Sekunden, Standard 10."
                ),
                validators=[MinValueValidator(2)],
                verbose_name="Update-Intervall Velocity-RCON (s)",
            ),
        ),
    ]
