# Generated by Django 5.2.11 on 2026-08-02 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_manage_auth_failover(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    ContentType = apps.get_model("contenttypes", "ContentType")

    ct = ContentType.objects.get(app_label="minecraft", model="minecraftintegrationconfig")
    perm, _ = Permission.objects.get_or_create(
        content_type=ct,
        codename="manage_auth_failover",
        defaults={"name": "Auth-Failover / Playerdata-Transfer"},
    )
    for group_name in ("mcc_operator", "Operatoren"):
        group = Group.objects.filter(name=group_name).first()
        if group is not None:
            group.permissions.add(perm)


def revoke_manage_auth_failover(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ct = ContentType.objects.filter(
        app_label="minecraft", model="minecraftintegrationconfig"
    ).first()
    if ct is None:
        return
    perm = Permission.objects.filter(
        content_type=ct, codename="manage_auth_failover"
    ).first()
    if perm is None:
        return
    for group in Group.objects.filter(name__in=["mcc_operator", "Operatoren"]):
        group.permissions.remove(perm)
    perm.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0035_session_login_wait_seconds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="minecraftintegrationconfig",
            options={
                "permissions": [
                    ("access_minecraft_control", "Control öffnen"),
                    ("access_minecraft_city", "Stadtsteuerung öffnen"),
                    ("access_minecraft_shop", "Shop-Betrieb öffnen"),
                    ("run_free_rcon", "Freie RCON-Befehle senden"),
                    ("manage_player_sessions", "Spieler-Sessions verwalten"),
                    ("manage_builder_sessions", "Builder-Sessions verwalten"),
                    ("run_arena_sim", "Velo-Arena Simulation starten"),
                    ("manage_minecraft_proxy", "Velocity/Limbo steuern"),
                    ("manage_auth_failover", "Auth-Failover / Playerdata-Transfer"),
                ],
                "verbose_name": "Integration",
                "verbose_name_plural": "Integration",
            },
        ),
        migrations.AddField(
            model_name="minecraftintegrationconfig",
            name="auth_failback_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Letzter Failback"
            ),
        ),
        migrations.AddField(
            model_name="minecraftintegrationconfig",
            name="auth_failover_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Failover seit"
            ),
        ),
        migrations.AddField(
            model_name="minecraftintegrationconfig",
            name="auth_last_snapshot_dir",
            field=models.CharField(
                blank=True,
                help_text="Pfad des letzten Failover-/Migrate-Backups.",
                max_length=512,
                verbose_name="Letztes Playerdata-Backup",
            ),
        ),
        migrations.AddField(
            model_name="minecraftintegrationconfig",
            name="auth_ops_mode",
            field=models.CharField(
                choices=[
                    ("online", "Online (Microsoft)"),
                    ("failover", "Failover (Offline-Proxy)"),
                    ("recovery", "Recovery (Rücktransfer)"),
                ],
                default="online",
                help_text=(
                    "Operativer Modus für Microsoft-Auth-Failover. "
                    "Steuert Hinweise in der Admin-GUI; Velocity online-mode wird "
                    "über die Failover-Aktionen umgeschaltet."
                ),
                max_length=16,
                verbose_name="Auth-Betriebsmodus",
            ),
        ),
        migrations.AlterField(
            model_name="mcsession",
            name="ms_username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Online-Spielername für RCON während der Session.",
                max_length=32,
                verbose_name="Microsoft-Login (Session)",
            ),
        ),
        migrations.AlterField(
            model_name="minecraftplayaccount",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Wenn aus: nicht in Spieler-Sessions, Warteliste und API sichtbar.",
                verbose_name="Aktiv",
            ),
        ),
        migrations.AlterField(
            model_name="minecraftplayaccount",
            name="ms_username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Online-Gamertag am Velocity-Proxy für RCON/send.",
                max_length=32,
                verbose_name="Microsoft-Login",
            ),
        ),
        migrations.AlterField(
            model_name="minecraftplayaccount",
            name="ms_uuid",
            field=models.CharField(
                blank=True,
                help_text="Optional; Inventar hängt an der UUID.",
                max_length=36,
                verbose_name="Microsoft-UUID",
            ),
        ),
        migrations.AlterField(
            model_name="minecraftplayaccount",
            name="prefer_spectator",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Nächste Session startet im Spectator-Modus. Bei aktiver Session "
                    "per Toggle auf der Session-Kachel umschaltbar."
                ),
                verbose_name="Spectator-Modus bevorzugen",
            ),
        ),
        migrations.AlterField(
            model_name="minecraftteamregistration",
            name="ms_username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    "Online-Gamertag am Velocity-Proxy (z. B. mccpc01). "
                    "Scoreboard bleibt mc_username; RCON/send und Bridge-Override "
                    "nutzen diesen Login."
                ),
                max_length=32,
                verbose_name="Microsoft-Login",
            ),
        ),
        migrations.AlterField(
            model_name="minecraftteamregistration",
            name="ms_uuid",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Optional; Inventar/Shop hängen an der UUID. "
                    "Nach erstem Join ergänzbar."
                ),
                max_length=36,
                verbose_name="Microsoft-UUID",
            ),
        ),
        migrations.AlterField(
            model_name="minecraftteamregistration",
            name="prefer_spectator",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Nächste Session startet im Spectator-Modus. Bei aktiver Session "
                    "per Toggle auf der Session-Kachel umschaltbar."
                ),
                verbose_name="Spectator-Modus bevorzugen",
            ),
        ),
        migrations.CreateModel(
            name="MinecraftPlayerdataTransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("online_to_offline", "Online → Offline-Twin"),
                            ("offline_to_online", "Offline-Twin → Online"),
                            ("legacy_to_twin", "Legacy-Offline → MS-Offline-Twin"),
                        ],
                        max_length=32,
                    ),
                ),
                ("dry_run", models.BooleanField(default=True)),
                ("ok", models.BooleanField(default=False)),
                ("backup_dir", models.CharField(blank=True, max_length=512)),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Playerdata-Transfer",
                "verbose_name_plural": "Playerdata-Transfers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(grant_manage_auth_failover, revoke_manage_auth_failover),
    ]
