# Copyright (c) 2026 SAI-Lab / MyCyclingCity
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.11 on 2026-08-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0042_session_teleport_to_spawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcsession',
            name='spawn_offset_index',
            field=models.PositiveSmallIntegerField(db_default=0, default=0, help_text='Gitter-/Ring-Index beim Spawn-Teleport (0 = exakter Spawn).', verbose_name='Spawn-Versatz-Index'),
        ),
    ]
