# Generated by Django 5.2

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecraft", "0043_session_spawn_offset_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="minecraftintegrationconfig",
            name="arena_default_time_limit_minutes",
            field=models.PositiveIntegerField(
                default=5,
                help_text=(
                    "Standard-Zeitlimit für Velo-Rennen in der Arena-Steuerung "
                    "(wenn noch kein Wert in der laufenden Session gespeichert ist). "
                    "Nützlich, wenn das Zeitfeld auf älteren Browsern nicht änderbar ist. "
                    "Minimum 1, Standard 5."
                ),
                validators=[MinValueValidator(1)],
                verbose_name="Velo-Arena Default-Zeitlimit (Min.)",
            ),
        ),
    ]
