# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0016_device_arena_sim_allowed"),
        ("minecraft", "0044_arena_default_time_limit_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="minecraftarenalane",
            name="preferred_stations",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "IoT-Stationen, die bei „Aktive erkennen“ bevorzugt dieser Bahn "
                    "zugeordnet werden (z. B. kleine Räder → Bahn 1 und 2). "
                    "Leer = beliebige freie Session."
                ),
                related_name="preferred_arena_lanes",
                to="iot.device",
                verbose_name="Bevorzugte Stationen",
            ),
        ),
    ]
