# Generated by Django 5.2.11 on 2026-08-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_dynamo_energy_fields"),
        ("minecraft", "0045_arena_lane_preferred_stations"),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftShopPurchaseCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=64, verbose_name='Material')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Restmenge')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_purchase_credits', to='api.group', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Shop-Kaufguthaben',
                'verbose_name_plural': 'Shop-Kaufguthaben',
                'constraints': [models.UniqueConstraint(fields=('group', 'material'), name='minecraft_shop_purchase_credit_unique')],
            },
        ),
    ]
