# Generated by Django 5.2.11 on 2026-08-24 17:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0027_luanti_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuantiArenaMotionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Arena aktiv')),
                ('default_speed', models.FloatField(default=3.0, verbose_name='Standardgeschwindigkeit')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arena-Einstellungen',
                'verbose_name_plural': 'Arena-Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='LuantiBridgeConnection',
            fields=[
                ('server_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Server-ID')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Verbunden')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='Verbunden seit')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt gesehen')),
            ],
            options={
                'verbose_name': 'Bridge-Verbindung',
                'verbose_name_plural': 'Bridge-Verbindungen',
            },
        ),
        migrations.CreateModel(
            name='LuantiShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('enabled', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Shop-Kategorie',
                'verbose_name_plural': 'Shop-Kategorien',
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='LuantiAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(help_text='Luanti-Spielername (ohne Leerzeichen).', max_length=32, unique=True, verbose_name='Login-Name')),
                ('id_tag', models.CharField(help_text='Token für RFID-Session-Start.', max_length=50, unique=True, verbose_name='RFID-UID')),
                ('display_name', models.CharField(blank=True, max_length=64, verbose_name='Anzeigename')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
                ('allowed_modes', models.JSONField(default=list, help_text='Liste z. B. ["play","build"]. Leer = play+build.', verbose_name='Erlaubte Modi')),
                ('default_mode', models.CharField(choices=[('play', 'Spielen'), ('build', 'Bauen'), ('watch', 'Zuschauen')], default='play', max_length=16, verbose_name='Standard-Modus')),
                ('session_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Leer = globaler Standard.', null=True, verbose_name='Session-Dauer (Min.)')),
                ('session_unlimited', models.BooleanField(default=False, verbose_name='Unbegrenzte Session')),
                ('password_provisioned', models.BooleanField(default=False, verbose_name='Passwort auf Server gesetzt')),
                ('password_last_set_at', models.DateTimeField(blank=True, null=True, verbose_name='Passwort gesetzt am')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='luanti_accounts', to='api.group', verbose_name='TOP-Gruppe')),
            ],
            options={
                'verbose_name': 'Luanti-Account',
                'verbose_name_plural': 'Luanti-Accounts',
                'ordering': ['sort_order', 'login_name'],
            },
        ),
        migrations.CreateModel(
            name='LuantiArenaLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('start_x', models.FloatField(default=0)),
                ('start_y', models.FloatField(default=3)),
                ('start_z', models.FloatField(default=0)),
                ('direction_x', models.FloatField(default=1)),
                ('direction_y', models.FloatField(default=0)),
                ('direction_z', models.FloatField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('assigned_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_lanes', to='luanti.luantiaccount')),
            ],
            options={
                'verbose_name': 'Arena-Spur',
                'verbose_name_plural': 'Arena-Spuren',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LuantiCityPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('steps', models.JSONField(default=list, help_text='Liste semantischer Commands, z. B. [{"op":"set_time","value":6000}].', verbose_name='Schritte')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('enabled', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('requires_confirmation', models.BooleanField(default=True, verbose_name='Bestätigung')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_success', models.BooleanField(blank=True, null=True)),
                ('last_run_output', models.TextField(blank=True)),
                ('last_run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stadt-Preset',
                'verbose_name_plural': 'Stadt-Presets',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LuantiIntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_active_hint', models.CharField(blank=True, default='Session ist aktiv', max_length=200, verbose_name='Hinweis aktive Session')),
                ('default_session_minutes', models.PositiveIntegerField(default=45, verbose_name='Standard-Sessiondauer (Min.)')),
                ('session_add_minutes', models.PositiveIntegerField(default=15, verbose_name='Zeit hinzufügen (Min.)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Luanti-Konfiguration',
                'verbose_name_plural': 'Luanti-Konfiguration',
                'permissions': [('access_luanti_control', 'Control öffnen'), ('access_luanti_city', 'Stadtsteuerung öffnen'), ('access_luanti_shop', 'Shop öffnen'), ('access_luanti_arena', 'Arena/Loren öffnen'), ('manage_luanti_accounts', 'Accounts verwalten'), ('manage_luanti_sessions', 'Sessions verwalten'), ('manage_luanti_stations', 'Stationen verwalten')],
            },
        ),
        migrations.CreateModel(
            name='LuantiProtectedRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.SlugField(max_length=64, unique=True, verbose_name='Region-ID')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='Anzeigename')),
                ('world', models.CharField(default='world', max_length=64, verbose_name='Welt')),
                ('min_x', models.IntegerField()),
                ('min_y', models.IntegerField(default=-64)),
                ('min_z', models.IntegerField()),
                ('max_x', models.IntegerField()),
                ('max_y', models.IntegerField(default=320)),
                ('max_z', models.IntegerField()),
                ('protect_build', models.BooleanField(default=True, verbose_name='Bauen schützen')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('assigned_to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='luanti_regions', to='api.group', verbose_name='TOP-Gruppe')),
            ],
            options={
                'verbose_name': 'Geschützte Region',
                'verbose_name_plural': 'Geschützte Regionen',
                'ordering': ['sort_order', 'region_id'],
            },
        ),
        migrations.CreateModel(
            name='LuantiShopTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_tx_id', models.CharField(max_length=64, unique=True, verbose_name='Client-Tx-ID')),
                ('side', models.CharField(choices=[('buy', 'Kauf'), ('sell', 'Verkauf')], max_length=8)),
                ('login_name', models.CharField(db_index=True, max_length=32)),
                ('item_name', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('velos_delta', models.IntegerField(verbose_name='Velos-Delta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='luanti_shop_txs', to='api.group')),
            ],
            options={
                'verbose_name': 'Shop-Transaktion',
                'verbose_name_plural': 'Shop-Transaktionen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LuantiStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('hostname', models.CharField(blank=True, max_length=120, verbose_name='Hostname')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Standort')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktiv')),
                ('api_key', models.CharField(blank=True, help_text='Wird beim Speichern erzeugt, wenn leer.', max_length=64, unique=True, verbose_name='API-Key')),
                ('desired_config', models.JSONField(blank=True, default=dict, help_text='Launcher/Server-Einstellungen für den Station-Agent.', verbose_name='Desired Config')),
                ('reported_config', models.JSONField(blank=True, default=dict, verbose_name='Gemeldete Config')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt gesehen')),
                ('last_error', models.TextField(blank=True, verbose_name='Letzter Fehler')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_stations', to='luanti.luantiaccount', verbose_name='Standard-Account')),
            ],
            options={
                'verbose_name': 'Station (PC)',
                'verbose_name_plural': 'Stationen (PCs)',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LuantiSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_name', models.CharField(db_index=True, max_length=32, verbose_name='Login-Name')),
                ('mode', models.CharField(choices=[('play', 'Spielen'), ('build', 'Bauen'), ('watch', 'Zuschauen')], default='play', max_length=16, verbose_name='Modus')),
                ('status', models.CharField(choices=[('READY', 'Bereit'), ('ACTIVE', 'Aktiv'), ('FINISHED', 'Beendet')], db_index=True, default='READY', max_length=16, verbose_name='Status')),
                ('source', models.CharField(choices=[('admin', 'Admin-GUI'), ('rfid', 'RFID-Scan'), ('system', 'System')], default='admin', max_length=16, verbose_name='Quelle')),
                ('timestamp_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='0 = unbegrenzt.', verbose_name='Dauer (Minuten)')),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Geplantes Ende')),
                ('timestamp_end', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächliches Ende')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='luanti.luantiaccount', verbose_name='Account')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='luanti.luantistation', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Luanti-Session',
                'verbose_name_plural': 'Luanti-Sessions',
                'ordering': ['-timestamp_start'],
            },
        ),
        migrations.CreateModel(
            name='LuantiPlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('play', 'Spielen'), ('build', 'Bauen')], max_length=16, verbose_name='Modus')),
                ('payload', models.JSONField(default=list, verbose_name='Inventar (JSON)')),
                ('revision', models.PositiveIntegerField(default=0, verbose_name='Revision')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_server_id', models.CharField(blank=True, max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='luanti.luantiaccount', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Spieler-Inventar',
                'verbose_name_plural': 'Spieler-Inventare',
                'constraints': [models.UniqueConstraint(fields=('account', 'mode'), name='luanti_inventory_account_mode_unique')],
            },
        ),
        migrations.CreateModel(
            name='LuantiShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Luanti itemstring, z. B. mcl_core:diamond', max_length=128, verbose_name='Item-Name')),
                ('display_name', models.CharField(blank=True, max_length=128, verbose_name='Anzeigename')),
                ('buy_price_velos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kaufpreis (Velos)')),
                ('stack_size', models.PositiveIntegerField(default=1, verbose_name='Stack-Größe')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('enabled', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='luanti.luantishopcategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Shop-Artikel',
                'verbose_name_plural': 'Shop-Artikel',
                'ordering': ['category', 'sort_order', 'item_name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'item_name'), name='luanti_shop_item_unique')],
            },
        ),
        migrations.CreateModel(
            name='LuantiShopPurchaseCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=128, verbose_name='Item-Name')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Restmenge')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luanti_shop_credits', to='api.group', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Shop-Kaufguthaben',
                'verbose_name_plural': 'Shop-Kaufguthaben',
                'constraints': [models.UniqueConstraint(fields=('group', 'item_name'), name='luanti_shop_credit_unique')],
            },
        ),
    ]
