# Generated by Django 5.2.11 on 2026-08-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanti', '0002_seed_city_presets'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuantiWaitingPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Login-Name')),
                ('server_id', models.CharField(blank=True, max_length=64, verbose_name='Server-ID')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstmals gesehen')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt gesehen')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_entries', to='luanti.luantiaccount', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Wartender Spieler',
                'verbose_name_plural': 'Wartende Spieler',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
