# Generated by Django 5.2.11 on 2026-08-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanti', '0003_waiting_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuantiPendingCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(blank=True, db_index=True, help_text='Leer = für alle Server.', max_length=64, verbose_name='Server-ID')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Zugestellt')),
            ],
            options={
                'verbose_name': 'Ausstehender Bridge-Befehl',
                'verbose_name_plural': 'Ausstehende Bridge-Befehle',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['delivered_at', 'id'], name='luanti_luan_deliver_89a5e9_idx')],
            },
        ),
    ]
