# Generated by Django 5.2.11 on 2026-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanti', '0006_city_presets_clear_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='luantiaccount',
            name='login_password',
            field=models.CharField(blank=True, help_text='Klartext für Admin-Anzeige und Linux-Station-Launcher. Wird auch auf dem Luanti-Server gesetzt.', max_length=64, verbose_name='Login-Passwort'),
        ),
    ]
