# Generated by Django 5.2

from django.db import migrations, models


def seed_and_flag_presets(apps, schema_editor):
    LuantiCityPreset = apps.get_model("luanti", "LuantiCityPreset")
    seeds = [
        {
            "slug": "daytime",
            "name": "Tag",
            "category": "world",
            "description": "Helle Tageszeit, klares Wetter",
            "steps": [
                {"op": "set_weather", "value": "clear"},
                {"op": "set_time", "value": 6000},
                {"op": "chat", "message": "Es ist Tag."},
            ],
            "sort_order": 10,
            "is_system": True,
            "moderator_can_run": True,
            "requires_confirmation": False,
        },
        {
            "slug": "nighttime",
            "name": "Nacht",
            "category": "world",
            "description": "Mitternacht, klares Wetter",
            "steps": [
                {"op": "set_weather", "value": "clear"},
                {"op": "set_time", "value": 0},
                {"op": "chat", "message": "Es ist Nacht."},
            ],
            "sort_order": 20,
            "is_system": True,
            "moderator_can_run": True,
            "requires_confirmation": False,
        },
        {
            "slug": "session-bootstrap",
            "name": "Session-Start (Tag)",
            "category": "world",
            "description": "Wird beim Start einer Luanti-Session automatisch ausgeführt.",
            "steps": [
                {"op": "set_weather", "value": "clear"},
                {"op": "set_time", "value": 6000},
                {"op": "chat", "message": "Es ist Tag."},
            ],
            "sort_order": 5,
            "is_system": True,
            "moderator_can_run": False,
            "requires_confirmation": False,
        },
    ]
    for seed in seeds:
        obj, created = LuantiCityPreset.objects.get_or_create(
            slug=seed["slug"],
            defaults={
                "name": seed["name"],
                "category": seed["category"],
                "description": seed["description"],
                "steps": seed["steps"],
                "sort_order": seed["sort_order"],
                "enabled": True,
                "is_system": seed["is_system"],
                "moderator_can_run": seed["moderator_can_run"],
                "requires_confirmation": seed["requires_confirmation"],
            },
        )
        if not created:
            # Flag existing rows as system; keep operator-edited steps intact.
            LuantiCityPreset.objects.filter(pk=obj.pk).update(
                is_system=True,
                category=seed["category"],
                moderator_can_run=seed["moderator_can_run"],
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("luanti", "0007_account_login_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="luanticitypreset",
            name="category",
            field=models.CharField(
                choices=[("world", "Welt & Wetter"), ("other", "Sonstiges")],
                default="world",
                max_length=16,
                verbose_name="Kategorie",
            ),
        ),
        migrations.AddField(
            model_name="luanticitypreset",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Geschützt: Löschen/Slug nur mit System-Rechten.",
                verbose_name="System-Preset",
            ),
        ),
        migrations.AddField(
            model_name="luanticitypreset",
            name="moderator_can_run",
            field=models.BooleanField(
                default=False,
                help_text="Erlaubt Ausführen auch ohne change-Recht (Stadtsteuerung).",
                verbose_name="Moderator darf ausführen",
            ),
        ),
        migrations.AlterField(
            model_name="luanticitypreset",
            name="steps",
            field=models.JSONField(
                default=list,
                help_text=(
                    'Semantische Bridge-Commands, z. B. [{"op":"set_time","value":6000}]. '
                    "Im Preset-Editor als Zeilen bearbeitbar — nicht im Code verdrahtet."
                ),
                verbose_name="Schritte",
            ),
        ),
        migrations.AlterModelOptions(
            name="luanticitypreset",
            options={
                "ordering": ["sort_order", "name"],
                "permissions": [
                    ("run_citypreset", "Stadt-Preset ausführen"),
                    ("change_system_citypreset", "System-Stadt-Preset bearbeiten"),
                    ("delete_system_citypreset", "System-Stadt-Preset löschen"),
                ],
                "verbose_name": "Stadt-Preset",
                "verbose_name_plural": "Stadt-Presets",
            },
        ),
        migrations.RunPython(seed_and_flag_presets, noop_reverse),
    ]
