# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


def backfill_active_wallet(apps, schema_editor):
    LuantiAccount = apps.get_model("luanti", "LuantiAccount")
    for account in LuantiAccount.objects.all():
        if account.active_wallet_id:
            continue
        if account.assigned_to_group_id:
            LuantiAccount.objects.filter(pk=account.pk).update(
                active_wallet_id=account.assigned_to_group_id,
                wallet_mode="fixed",
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_luanti_integration"),
        ("luanti", "0008_city_preset_editor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="luantiaccount",
            name="assigned_to_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisation / TOP (Filter, Pool-Modus).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="luanti_accounts",
                to="api.group",
                verbose_name="Heimat-Gruppe",
            ),
        ),
        migrations.AddField(
            model_name="luantiaccount",
            name="active_wallet",
            field=models.ForeignKey(
                blank=True,
                help_text='Gruppe, deren velos_spendable belastet wird (bei Modus „Fest“).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="luanti_wallet_accounts",
                to="api.group",
                verbose_name="Aktives Wallet",
            ),
        ),
        migrations.AddField(
            model_name="luantiaccount",
            name="wallet_mode",
            field=models.CharField(
                choices=[
                    ("fixed", "Festes Wallet"),
                    ("auto_leaf", "Auto: Leaf mit meistem Spendable"),
                    ("pool", "Pool: Heimat-Gruppe"),
                ],
                default="fixed",
                max_length=16,
                verbose_name="Wallet-Modus",
            ),
        ),
        migrations.AddField(
            model_name="luantisession",
            name="wallet_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: überschreibt Account-Wallet nur für diese Session.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="luanti_session_wallets",
                to="api.group",
                verbose_name="Session-Wallet",
            ),
        ),
        migrations.RunPython(backfill_active_wallet, noop),
    ]
