# Generated by Django 5.2.11 on 2026-08-26 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_grant_transfer_group_velos'),
        ('luanti', '0014_session_end_warning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luantiprotectedregion',
            options={'ordering': ['sort_order', 'region_id'], 'permissions': [('manage_luanti_regions', 'Geschützte Regionen verwalten')], 'verbose_name': 'Geschützte Region', 'verbose_name_plural': 'Geschützte Regionen'},
        ),
        migrations.AddField(
            model_name='luantiprotectedregion',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Accounts, die im Build-Modus in dieser Region bauen dürfen.', related_name='protected_regions', to='luanti.luantiaccount', verbose_name='Mitglieder (Accounts)'),
        ),
        migrations.AddField(
            model_name='luantiprotectedregion',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notiz'),
        ),
        migrations.AddField(
            model_name='luantiprotectedregion',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leer = Master-Region. Gesetzt = Subregion innerhalb der Master-Bounds.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='luanti.luantiprotectedregion', verbose_name='Master-Region'),
        ),
        migrations.AddField(
            model_name='luantiprotectedregion',
            name='spawn_x',
            field=models.IntegerField(blank=True, help_text='Optionaler Session-Spawn. Leer = Cuboid-Mitte.', null=True, verbose_name='Spawn X'),
        ),
        migrations.AddField(
            model_name='luantiprotectedregion',
            name='spawn_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Spawn Y'),
        ),
        migrations.AddField(
            model_name='luantiprotectedregion',
            name='spawn_z',
            field=models.IntegerField(blank=True, null=True, verbose_name='Spawn Z'),
        ),
        migrations.AddField(
            model_name='luantiprotectedregion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='luantiprotectedregion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Geändert von'),
        ),
        migrations.AlterField(
            model_name='luantiaccount',
            name='allowed_modes',
            field=models.JSONField(default=list, help_text='Liste z. B. ["play","build","watch"]. Leer = alle drei.', verbose_name='Erlaubte Modi'),
        ),
        migrations.AlterField(
            model_name='luantiprotectedregion',
            name='assigned_to_group',
            field=models.ForeignKey(blank=True, help_text='Nur bei Master-Regionen: permanente Zuordnung zur TOP-Gruppe. Subregionen erben über die Master-Region.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='luanti_regions', to='api.group', verbose_name='TOP-Gruppe'),
        ),
        migrations.AlterField(
            model_name='luantiprotectedregion',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='luantiprotectedregion',
            name='max_x',
            field=models.IntegerField(verbose_name='Max X'),
        ),
        migrations.AlterField(
            model_name='luantiprotectedregion',
            name='max_y',
            field=models.IntegerField(default=320, verbose_name='Max Y'),
        ),
        migrations.AlterField(
            model_name='luantiprotectedregion',
            name='max_z',
            field=models.IntegerField(verbose_name='Max Z'),
        ),
        migrations.AlterField(
            model_name='luantiprotectedregion',
            name='min_x',
            field=models.IntegerField(verbose_name='Min X'),
        ),
        migrations.AlterField(
            model_name='luantiprotectedregion',
            name='min_y',
            field=models.IntegerField(default=-64, verbose_name='Min Y'),
        ),
        migrations.AlterField(
            model_name='luantiprotectedregion',
            name='min_z',
            field=models.IntegerField(verbose_name='Min Z'),
        ),
        migrations.AlterField(
            model_name='luantiprotectedregion',
            name='protect_build',
            field=models.BooleanField(default=True, help_text='Wenn aktiv: im Build-Modus dürfen nur Members in diesem Cuboid bauen. Aus = Passthrough (kein eigener Bau-Schutz).', verbose_name='Bauen schützen'),
        ),
        migrations.AlterField(
            model_name='luantiprotectedregion',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Reihenfolge in der Liste (Master untereinander, Subs je Master).', verbose_name='Sortierung'),
        ),
    ]
