# Generated by Django 5.2.11 on 2026-08-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanti', '0015_protected_region_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuantiPlayerPosReply',
            fields=[
                ('request_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Spielerpositions-Antwort',
                'verbose_name_plural': 'Spielerpositions-Antworten',
            },
        ),
    ]
