# Generated by Django 5.2.11 on 2026-08-26 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanti', '0016_player_pos_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='luantiintegrationconfig',
            name='region_outline_enabled',
            field=models.BooleanField(default=True, help_text='Cuboid-Grenzen als Partikel in der Nähe von Spielern zeichnen.', verbose_name='Regionen-Markierung aktiv'),
        ),
        migrations.AddField(
            model_name='luantiintegrationconfig',
            name='region_outline_enter_hint',
            field=models.BooleanField(default=True, help_text='Region-Namen kurz anzeigen, wenn ein Spieler eine Zone betritt.', verbose_name='Hinweis beim Betreten'),
        ),
        migrations.AddField(
            model_name='luantiintegrationconfig',
            name='region_outline_view_distance',
            field=models.PositiveIntegerField(default=48, help_text='Horizontale Distanz, ab der Outline-Partikel gezeichnet werden.', validators=[django.core.validators.MinValueValidator(8)], verbose_name='Sichtweite Regionen (Blöcke)'),
        ),
    ]
