# Copyright (c) 2026 SAI-Lab / MyCyclingCity
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# @file    0001_initial.py
# @author  Roland Rutz
# @note    This code was developed with the assistance of AI (LLMs).

#
# Generated by Django 5.2.9 on 2026-01-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(editable=False, help_text='Eindeutiger Code für diesen Spiel-Raum', max_length=8, unique=True, verbose_name='Raum-Code')),
                ('master_session_key', models.CharField(blank=True, help_text='Session-Key des Spielleiters (Masters)', max_length=40, null=True, verbose_name='Master Session Key')),
                ('is_active', models.BooleanField(default=True, help_text='Ob dieser Raum aktiv ist oder beendet wurde', verbose_name='Aktiv')),
                ('device_assignments', models.JSONField(blank=True, default=dict, help_text="Mapping von Gerätenamen zu Cyclist user_id (z.B. {'device1': 'cyclist1'})", verbose_name='Geräte-Zuweisungen')),
                ('start_distances', models.JSONField(blank=True, default=dict, help_text="Distanzen der Cyclists beim Spielstart (z.B. {'cyclist1': 100.5})", verbose_name='Start-Distanzen')),
                ('stop_distances', models.JSONField(blank=True, default=dict, help_text="Distanzen der Cyclists beim Spielstopp (z.B. {'cyclist1': 150.2})", verbose_name='Stop-Distanzen')),
                ('is_game_stopped', models.BooleanField(default=False, help_text='Ob das Spiel gestoppt wurde', verbose_name='Spiel gestoppt')),
                ('announced_winners', models.JSONField(blank=True, default=list, help_text='Liste der user_ids von Cyclists, die bereits als Gewinner angekündigt wurden', verbose_name='Angekündigte Gewinner')),
                ('current_target_km', models.FloatField(default=0.0, help_text='Das aktuelle Ziel in Kilometern für dieses Spiel', verbose_name='Aktuelles Ziel (km)')),
                ('active_sessions', models.JSONField(blank=True, default=list, help_text='Liste der Session-Keys, die aktuell diesem Raum beigetreten sind', verbose_name='Aktive Sessions')),
                ('session_to_cyclist', models.JSONField(blank=True, default=dict, help_text='Mapping von Session-Keys zu Cyclist user_ids (für Master-Transfer)', verbose_name='Session zu Cyclist Mapping')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aktivität in diesem Raum', verbose_name='Letzte Aktivität')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Spiel-Raum',
                'verbose_name_plural': 'Spiel-Räume',
                'ordering': ['-created_at'],
            },
        ),
    ]
