# Generated by Django 5.2.9 on 2026-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Django Session Key', max_length=40, unique=True, verbose_name='Session Key')),
                ('room_code', models.CharField(blank=True, db_index=True, help_text='Raum-Code, falls die Session in einem Raum ist', max_length=8, null=True, verbose_name='Raum-Code')),
                ('is_master', models.BooleanField(default=False, help_text='Ob diese Session die Master-Session ist', verbose_name='Master')),
                ('has_assignments', models.BooleanField(default=False, help_text='Ob diese Session Geräte-Zuweisungen hat', verbose_name='Hat Zuweisungen')),
                ('has_target_km', models.BooleanField(default=False, help_text='Ob diese Session ein Ziel-Kilometer gesetzt hat', verbose_name='Hat Ziel-KM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Zuletzt aktualisiert')),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
                'ordering': ['-last_updated'],
                'indexes': [
                    models.Index(fields=['room_code', 'is_master'], name='game_gamese_room_co_528e39_idx'),
                    models.Index(fields=['has_assignments', 'has_target_km'], name='game_gamese_has_ass_e84650_idx'),
                ],
            },
        ),
    ]
