# Generated by Django 5.2.9 on 2026-02-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_session_gamesession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameroom',
            options={'ordering': ['-created_at'], 'verbose_name': 'Spielraum', 'verbose_name_plural': 'Spielräume'},
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='active_sessions',
            field=models.JSONField(blank=True, default=list, help_text='Liste von Sitzungsschlüsseln, die diesem Raum aktuell beigetreten sind', verbose_name='Aktive Sitzungen'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='announced_winners',
            field=models.JSONField(blank=True, default=list, help_text='Liste von User-IDs der Radfahrer, die bereits als Gewinner bekanntgegeben wurden', verbose_name='Bekanntgegebene Gewinner'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='device_assignments',
            field=models.JSONField(blank=True, default=dict, help_text="Zuordnung von Gerätenamen zu Radfahrer-User-IDs (z.B. {'device1': 'cyclist1'})", verbose_name='Gerätezuweisungen'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='master_session_key',
            field=models.CharField(blank=True, help_text='Sitzungsschlüssel des Spielleiters', max_length=40, null=True, verbose_name='Spielleiter-Sitzungsschlüssel'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_code',
            field=models.CharField(editable=False, help_text='Eindeutiger Code für diesen Spielraum', max_length=8, unique=True, verbose_name='Raum-Code'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='session_to_cyclist',
            field=models.JSONField(blank=True, default=dict, help_text='Zuordnung von Sitzungsschlüsseln zu Radfahrer-User-IDs (für Spielleiter-Übertragung)', verbose_name='Sitzung zu Radfahrer Zuordnung'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='start_distances',
            field=models.JSONField(blank=True, default=dict, help_text="Entfernungen der Radfahrer beim Spielstart (z.B. {'cyclist1': 100.5})", verbose_name='Startentfernungen'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='stop_distances',
            field=models.JSONField(blank=True, default=dict, help_text="Entfernungen der Radfahrer beim Spielstopp (z.B. {'cyclist1': 150.2})", verbose_name='Stoppentfernungen'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='has_assignments',
            field=models.BooleanField(default=False, help_text='Ob diese Sitzung Gerätezuweisungen hat', verbose_name='Hat Zuweisungen'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='has_target_km',
            field=models.BooleanField(default=False, help_text='Ob diese Sitzung ein Zielkilometer gesetzt hat', verbose_name='Hat Ziel-KM'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='is_master',
            field=models.BooleanField(default=False, help_text='Ob diese Sitzung die Spielleiter-Sitzung ist', verbose_name='Spielleiter'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='room_code',
            field=models.CharField(blank=True, db_index=True, help_text='Raum-Code, falls die Sitzung in einem Raum ist', max_length=8, null=True, verbose_name='Raum-Code'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='session_key',
            field=models.CharField(db_index=True, help_text='Django Sitzungsschlüssel', max_length=40, unique=True, verbose_name='Sitzungsschlüssel'),
        ),
    ]
