# Generated by Django 5.2.9 on 2026-01-22 12:22
# Fixed: Don't create django_session table if it already exists

import django.contrib.sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_session_gamesession'),
    ]

    operations = [
        # Only update model state, don't create the table (it's managed by sessions app)
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No database operations - table already exists
            state_operations=[
                # Create the model state for Django's ORM (this doesn't create the table)
                migrations.CreateModel(
                    name='Session',
                    fields=[
                        ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                        ('session_data', models.TextField(verbose_name='session data')),
                        ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                    ],
                    options={
                        'verbose_name': 'session',
                        'verbose_name_plural': 'sessions',
                        'db_table': 'django_session',
                        'abstract': False,
                        'managed': False,  # Don't manage this table, it's managed by sessions app
                    },
                    managers=[
                        ('objects', django.contrib.sessions.models.SessionManager()),
                    ],
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Game Session Tracking', 'verbose_name_plural': 'Game Session Tracking'},
        ),
    ]
