# Generated by Django 5.2.9 on 2026-01-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_session_alter_gamesession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
    ]
