# Generated by Django 5.2.9 on 2026-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_velos_target'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gamesession',
            name='game_gamese_has_ass_e84650_idx',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='round_duration_seconds',
            field=models.PositiveIntegerField(default=300, verbose_name='Rundendauer (Sekunden)'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='round_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rundenstart'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='timer_auto_stop',
            field=models.BooleanField(default=False, verbose_name='Auto-Stopp bei Timer-Ablauf'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='timer_enabled',
            field=models.BooleanField(default=False, verbose_name='Runden-Timer aktiv'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='timer_highlight_last_minute',
            field=models.BooleanField(default=True, verbose_name='Letzte Minute hervorheben'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='timer_sound_enabled',
            field=models.BooleanField(default=True, verbose_name='Timer-Ton aktiv'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='has_target_velos',
            field=models.BooleanField(default=False, help_text='Ob diese Sitzung ein Velos-Ziel gesetzt hat', verbose_name='Hat Velos-Ziel'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['has_assignments', 'has_target_velos'], name='game_gamese_has_ass_07e3d1_idx'),
        ),
    ]
