# Generated by Django 5.2.9 on 2026-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_fezitty_game_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='timer_expired',
            field=models.BooleanField(default=False, verbose_name='Timer abgelaufen (Hinweis aktiv)'),
        ),
    ]
